import { Person, Tense } from "./types";

export const verbEndings: {
  [key in Tense]?: {
    [key: string]: { [key in Person]: string };
  };
} = {
  Present: {
    ar: {
      yo: "o",
      tú: "ás",
      "él/ella/Ud.": "á",
      nosotros: "amos",
      vosotros: "áis",
      "ellos/ellas/Uds.": "án",
    },
    er: {
      yo: "o",
      tú: "es",
      "él/ella/Ud.": "e",
      nosotros: "emos",
      vosotros: "éis",
      "ellos/ellas/Uds.": "en",
    },
    ir: {
      yo: "o",
      tú: "es",
      "él/ella/Ud.": "e",
      nosotros: "imos",
      vosotros: "ís",
      "ellos/ellas/Uds.": "en",
    },
  },
  Preterite: {
    ar: {
      yo: "e",
      tú: "aste",
      "él/ella/Ud.": "o",
      nosotros: "amos",
      vosotros: "asteis",
      "ellos/ellas/Uds.": "aron",
    },
    er: {
      yo: "e",
      tú: "iste",
      "él/ella/Ud.": "o",
      nosotros: "imos",
      vosotros: "isteis",
      "ellos/ellas/Uds.": "ieron",
    },
    ir: {
      yo: "e",
      tú: "iste",
      "él/ella/Ud.": "o",
      nosotros: "imos",
      vosotros: "isteis",
      "ellos/ellas/Uds.": "ieron",
    },
  },
  Imperfect: {
    ar: {
      yo: "aba",
      tú: "abas",
      "él/ella/Ud.": "aba",
      nosotros: "ábamos",
      vosotros: "abais",
      "ellos/ellas/Uds.": "aban",
    },
    er: {
      yo: "ía",
      tú: "ías",
      "él/ella/Ud.": "ía",
      nosotros: "íamos",
      vosotros: "íais",
      "ellos/ellas/Uds.": "ían",
    },
    ir: {
      yo: "ía",
      tú: "ías",
      "él/ella/Ud.": "ía",
      nosotros: "íamos",
      vosotros: "íais",
      "ellos/ellas/Uds.": "ían",
    },
  },
  Future: {
    ar: {
      yo: "é",
      tú: "ás",
      "él/ella/Ud.": "á",
      nosotros: "emos",
      vosotros: "éis",
      "ellos/ellas/Uds.": "án",
    },
    er: {
      yo: "é",
      tú: "ás",
      "él/ella/Ud.": "á",
      nosotros: "emos",
      vosotros: "éis",
      "ellos/ellas/Uds.": "án",
    },
    ir: {
      yo: "é",
      tú: "ás",
      "él/ella/Ud.": "á",
      nosotros: "emos",
      vosotros: "éis",
      "ellos/ellas/Uds.": "án",
    },
  },
  Conditional: {
    ar: {
      yo: "ía",
      tú: "ías",
      "él/ella/Ud.": "ía",
      nosotros: "íamos",
      vosotros: "íais",
      "ellos/ellas/Uds.": "ían",
    },
    er: {
      yo: "ía",
      tú: "ías",
      "él/ella/Ud.": "ía",
      nosotros: "íamos",
      vosotros: "íais",
      "ellos/ellas/Uds.": "ían",
    },
    ir: {
      yo: "ía",
      tú: "ías",
      "él/ella/Ud.": "ía",
      nosotros: "íamos",
      vosotros: "íais",
      "ellos/ellas/Uds.": "ían",
    },
  },
};

export const irregularStemsPresent: { [key: string]: string } = {
  ir: "v",
  ser: "s",
  estar: "est",
  haber: "h",
  tener: "tien",
  venir: "vien",
  poder: "pued",
  querer: "quier",
  decir: "dic",
  hacer: "hac",
  poner: "pon",
  saber: "sab",
  traer: "tra",
  dar: "d",
  ver: "ve",
  sentir: "sient",
  dormir: "duerm",
  morir: "muer",
  pensar: "piens",
  perder: "pierd",
  encontrar: "encuentr",
  volver: "vuelv",
  contar: "cuent",
  mostrar: "muestr",
  recordar: "recuerd",
  mover: "muev",
  almorzar: "almuerz",
  jugar: "jueg",
  pedir: "pid",
  servir: "sirv",
  repetir: "repit",
  seguir: "sig",
  conseguir: "consig",
  preferir: "prefier",
};

export const irregularStemsPreterite: { [key: string]: string } = {
  poder: "pud",
  poner: "pus",
  saber: "sup",
  querer: "quis",
  venir: "vin",
  tener: "tuv",
  estar: "estuv",
  hacer: "hic",
  decir: "dij",
  traer: "traj",
  andar: "anduv",
  caber: "cup",
  haber: "hub",
  producir: "produj",
  conducir: "conduj",
  traducir: "traduj",
  dormir: "durm",
  morir: "mur",
  ir: "fu",
  ser: "fu",
  dar: "d",
  ver: "v",
  caer: "cay",
  oír: "oy",
  leer: "ley",
  sentir: "sint",
  convertir: "convirt",
  mentir: "mint",
  preferir: "prefir",
};

export const irregularStemsImperfect: { [key: string]: string } = {
  ir: "i",
  ver: "ve",
  ser: "er",
};
export const irregularStemsFutureConditional: { [key: string]: string } = {
  decir: "dir",
  hacer: "har",
  poder: "podr",
  poner: "pondr",
  querer: "querr",
  saber: "sabr",
  salir: "saldr",
  tener: "tendr",
  valer: "valdr",
  venir: "vendr",
  haber: "habr",
  caber: "cabr",
};
